package org.litote.openapi.ktor.client.generator

import org.litote.openapi.ktor.client.generator.adapter.parser.OpenApiSpecificationParser
import org.litote.openapi.ktor.client.generator.adapter.renderer.ApiModelGenerator
import org.litote.openapi.ktor.client.generator.domain.ClientSpec
import org.litote.openapi.ktor.client.generator.domain.GeneratedFileSpec
import org.litote.openapi.ktor.client.generator.domain.ModelSpec
import java.nio.file.Files
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class ModuleTransformTest {
    private val testSpec = "src/test/resources/openapi.json"

    @Test
    fun `GIVEN module with transformFile WHEN generating THEN all generated files contain the transformation`() {
        val outputDir = Files.createTempDirectory("module-transform-file-test").toFile()
        try {
            val headerComment = "// Generated by test module"
            val module =
                object : ApiGeneratorModule {
                    override fun transformFile(file: GeneratedFileSpec): GeneratedFileSpec =
                        file.copy(content = "$headerComment\n" + file.content)
                }
            val config =
                ApiGeneratorConfiguration(
                    openApiFile = testSpec,
                    outputDirectory = outputDir.absolutePath,
                    modules = listOf(module),
                )

            val result = generate(config)

            assertTrue(result.isSuccess, "Generation should succeed")
            val generatedFiles = outputDir.walkTopDown().filter { it.isFile && it.extension == "kt" }.toList()
            assertTrue(generatedFiles.isNotEmpty(), "Should generate at least one file")
            assertTrue(
                generatedFiles.all { it.readText().startsWith(headerComment) },
                "All generated files should start with the header comment",
            )
        } finally {
            outputDir.deleteRecursively()
        }
    }

    @Test
    fun `GIVEN module with transformClientSpec WHEN generating THEN hook is called for each client`() {
        val outputDir = Files.createTempDirectory("module-transform-client-test").toFile()
        try {
            val visitedClients = mutableListOf<String>()
            val module =
                object : ApiGeneratorModule {
                    override fun transformClientSpec(spec: ClientSpec): ClientSpec {
                        visitedClients.add(spec.name)
                        return spec.copy(operations = emptyList())
                    }
                }
            val config =
                ApiGeneratorConfiguration(
                    openApiFile = testSpec,
                    outputDirectory = outputDir.absolutePath,
                    modules = listOf(module),
                )

            val result = generate(config)

            assertTrue(result.isSuccess, "Generation should succeed")
            assertTrue(visitedClients.isNotEmpty(), "transformClientSpec should have been called for each client")
            val generatedFiles = outputDir.walkTopDown().filter { it.isFile && it.extension == "kt" }.toList()
            // Client files are generated but contain no operation functions (only the constructor property)
            val clientFiles =
                generatedFiles.filter { file ->
                    visitedClients.any { clientName -> file.name == "$clientName.kt" }
                }
            assertTrue(clientFiles.isNotEmpty(), "Client files should be generated")
        } finally {
            outputDir.deleteRecursively()
        }
    }

    @Test
    fun `GIVEN module with transformModelSpec WHEN building model THEN transform is applied`() {
        val configuration =
            ApiGeneratorConfiguration(
                openApiFile = testSpec,
                outputDirectory = "build/openapi-test",
            )
        val spec = OpenApiSpecificationParser(configuration).parse(configuration.operationFilter)
        val dataClassSpec = spec.models.filterIsInstance<ModelSpec.DataClassSpec>().first()
        val transformedName = "TransformedModel"
        val module =
            object : ApiGeneratorModule {
                override fun transformModelSpec(spec: ModelSpec): ModelSpec =
                    if (spec is ModelSpec.DataClassSpec && spec.name == dataClassSpec.name) {
                        spec.copy(name = transformedName)
                    } else {
                        spec
                    }
            }
        val generator =
            ApiModelGenerator(
                configuration.modelPackage,
                "build/openapi-test",
                modules = listOf(module),
            )

        val typeSpec = generator.buildModel(dataClassSpec)

        assertNotNull(typeSpec, "buildModel should return a TypeSpec")
        assertEquals(transformedName, typeSpec.name, "Model name should be the transformed name")
    }
}
